apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: to-do-app-tls
  namespace: default
spec:
  secretName: to-do-app-tls
  dnsNames:
  - devopscrew.tech
  - www.devopscrew.tech
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
