apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: to-do-app
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
        - devopscrew.tech
        - www.devopscrew.tech
      secretName: to-do-app-tls
  rules:
    - host: "devopscrew.tech"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: to-do-app
                port:
                  number: 80
    - host: "www.devopscrew.tech"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: to-do-app
                port:
                  number: 80
